name: tox

on:
  create: # is used for publishing to PyPI and TestPyPI
    tags: # any tag regardless of its name, no branches
      - "**"
  push: # only publishes pushes to the main branch to TestPyPI
    branches: # any integration branch but not tag
      - "main"
  pull_request:

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: lint
            python-version: "3.9"
          - name: packaging
            python-version: "3.9"
          - name: py37
            python-version: "3.7"
          - name: py38
            python-version: "3.8"
          - name: py39
            python-version: "3.9"
          - name: py310
            python-version: "3.10"
          - name: py311
            python-version: "~3.11.0-0"

    env:
      FORCE_COLOR: 1

    steps:
      - name: Check out src from Git
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed by setuptools-scm

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-commit cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ matrix.name }}-pre-commit-${{ hashFiles('setup.cfg', 'tox.ini', 'pyproject.toml', '.pre-commit-config.yaml') }}

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.name }}-pip-${{ hashFiles('setup.cfg', 'tox.ini', 'pyproject.toml', '.pre-commit-config.yaml') }}

      - name: Install tox
        run: python3 -m pip install --upgrade tox

      - name: Log installed dists
        run: python -m pip freeze --all

      - name: tox -e ${{ matrix.name }}
        run: python3 -m tox -e ${{ matrix.name }}

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs.zip
          path: .tox/**/log/

  check: # This job does nothing and is only used for the branch protection
    if: always()

    needs:
      - tox

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
